CREATE TABLE menu_group(
	mgid INT(10) NOT NULL AUTO_INCREMENT,
	gid INT(9) NOT NULL COMMENT '组id',
	menuid INT(9) NOT NULL COMMENT '菜单id',
	operate_time DATETIME,
	operate_people VARCHAR(20)NOT NULL DEFAULT 'admin' COMMENT '操作人',
	PRIMARY KEY(mgid),
	FOREIGN KEY(gid) REFERENCES groups(gid) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(menuid) REFERENCES menu_tree(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8;
